SELECT MONTH(GETDATE()

SELECT BirthDate, MONTH(BirthDate) FROM DimEmployee

select DAY(GETDATE())

select BirthDate, DAY(BirthDate) FROM DimEmployee


SELECT DATEPART(YYYY,GETDATE())

SELECT DATEPART(MM,GETDATE())

SELECT DATEPART(DD,GETDATE())

SELECT DATEPART(WEEKDAY,GETDATE())  -- RETURN INTEGER

SELECT DATENAME(YYYY,GETDATE()) -- RETURN VARCHAR

SELECT DATENAME(MM,GETDATE()) -- RETUTN VARCHAR

SELECT DATENAME(WEEKDAY,GETDATE())
 

SELECT FORMAT(GETDATE(),'yy')  -- format are case-sensitive 'yy' use lower
SELECT FORMAT(GETDATE(),'MM') -- upper case for month
SELECT FORMAT(GETDATE(),'MMM')
SELECT FORMAT(GETDATE(),'MMMM')

SELECT FORMAT(GETDATE(),'hh')

SELECT FORMAT(GETDATE(),'dd-MMM-yyy hh:mm:ss') -- you are just
-- formating not changing changing underlying value ok.


SELECT DATEADD(YEAR,1,GETDATE()) -- ADD 1 IN CURRENT YEAR 2026 + 1 = 2027

SELECT DATEADD(YEAR,5,GETDATE()) 

SELECT DATEDIFF(YEAR,DATEFROMPARTS(2010,1,1),GETDATE()) 

SELECT DATEDIFF(MM,DATEFROMPARTS(2010,1,1),GETDATE()) 

SELECT DATEDIFF(DD,DATEFROMPARTS(2010,1,1),GETDATE()) 


SELECT EOMONTH(GETDATE(),0) -- END OF MONTH FUNC AND SECOND PARAMETER TAKE INTEGER
-- SECOND PARAM ADD 0 TO MONTH

SELECT EOMONTH(GETDATE(),1) 

SELECT EOMONTH(GETDATE(),-1) 


